name: Python CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Run tests
              run: |
                  cd Sprint1/Lab5
                  python -m unittest sum_test.py
                  python -m unittest subtract_test.py
                  python -m unittest multiply_test.py
                  python -m unittest division_test.py
